import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import Wrapper from "@/Layouts/Wrapper";
import Form from "@/components/Form";
import Footer from "@/Layouts/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bismillah Multi-Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* main div */}

      <Wrapper>
        <Form />
        <Footer />
      </Wrapper>
    </>
  );
}
